# Generated by Django 4.0.2 on 2022-02-09 15:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_vote_to_skip_room_votes_to_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_id',
            field=models.CharField(default=api.models.generate_id, max_length=10, unique=True),
        ),
    ]
